publish_event:
  # Description of the service
  description: Publish events to the MQTT topic
  # Different fields that your service accepts
  fields:
    # Key of the field
    payload:
      # Description of the field
      description: MQTT payload as string
      # Example value that can be passed for this field
      example: ""
